/uwb_localization:
  ros__parameters:
    base_link: base_link
    global_link: map
    initial_pos:
      - 0.0
      - 0.0 
      - 0.0
    pos_covariance:
      - 0.1
      - 0.1 
      - 0.1
    squared_cost: true
    two_d_mode: false
    verbose: true