/uwb_localization:
  ros__parameters:
    base_link: uwb_1_link
    global_link: world
    initial_pos:
      - 0.0
      - 0.0
      - 0.0
    pos_covariance:
      - 0.1
      - 0.1 
      - 0.1
    squared_cost: false
    two_d_mode: false
    use_tag_estimate: false
    verbose: false
    visual_debug: true